name    'lcgdm-dmlite'
version '0.3.3'
source 'UNKNOWN'
author 'DPM'
license 'Apache License, Version 2.0'
summary 'Package for managing dmlite plugins'
description 'This package provides modules for managing dmlite'
project_page 'https://svnweb.cern.ch/trac/lcgdm'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'CERNOps/fetchcrl', '>= 0.1.0'
dependency 'puppetlabs/stdlib', '>= 2.0.0'
