class dmlite::dav::params (
) inherits dmlite::params {
    $dmlite_conf        = hiera('dmlite::dav::params::dmlite_conf','/etc/dmlite.conf')
    $dmlite_disk_conf   = hiera('dmlite::dav::params::dmlite_disk_conf','/etc/dmlite-disk.conf')
    $ns_type            = hiera('dmlite::dav::params::ns_type', 'Head')
    $ns_prefix          = hiera('dmlite::dav::params::ns_prefix', 'dpm')
    $disk_prefix        = hiera('dmlite::dav::params::disk_prefix', 'dpm')
    $ns_flags           = hiera('dmlite::dav::params::ns_flags', 'Write RemoteCopy')
    $ns_anon            = hiera('dmlite::dav::params::ns_anon', false)
    $ns_max_replicas    = hiera('dmlite::dav::params::ns_max_replicas', 3)
    $ns_secure_redirect = hiera('dmlite::dav::params::ns_secure_redirect', 'Off')
    $ns_trusted_dns     = hiera('dmlite::dav::params::ns_trusted_dns', undef)
    $ns_macaroon_secret = hiera('dmlite::dav::params::ns_macaroon_secret', false)
    $disk_flags         = hiera('dmlite::dav::params::disk_flags', 'Write RemoteCopy')
    $disk_anon          = hiera('dmlite::dav::params::disk_anon', 'nobody:nogroup')
    $ssl_cert           = hiera('dmlite::dav::params::ssl_cert', '/etc/grid-security/hostcert.pem')
    $ssl_key            = hiera('dmlite::dav::params::ssl_key', '/etc/grid-security/hostkey.pem')
    $ssl_capath         = hiera('dmlite::dav::params::ssl_capath', '/etc/grid-security/certificates')
    $ssl_ciphersuite    = hiera('dmlite::dav::params::ssl_ciphersuite', 'NULL-MD5:NULL:RC4-MD5:RC4:+LOW:+MEDIUM:+HIGH:+EXP')
    $ssl_options        = hiera('dmlite::dav::params::ssl_options','+StdEnvVars')
    $log_error          = hiera('dmlite::dav::params::log_error', 'logs/ssl_error_log')
    $log_transfer       = hiera('dmlite::dav::params::log_transfer', 'logs/ssl_access_log')
    $log_level          = hiera('dmlite::dav::params::log_level','warn')
    $user               = hiera('dmlite::dav::params::user', 'dpmmgr')
    $group              = hiera('dmlite::dav::params::group','dpmmgr')
    $coredump_dir       = hiera('dmlite::dav::params::coredump_dir', undef)
    $ulimit             = hiera('dmlite::dav::params::ulimit', undef)
    $enable_ns          = hiera('dmlite::dav::params::enable_ns',true)
    $enable_disk        = hiera('dmlite::dav::params::enable_disk', true)
    $enable_https       = hiera('dmlite::dav::params::enable_https', true)
    $enable_http        = hiera('dmlite::dav::params::enable_http', true)
    $enable_keep_alive  = hiera('dmlite::dav::params::enable_keep_alive', true)
    $mpm_model          = hiera('dmlite::dav::params::mpm_model', '/usr/sbin/httpd.event')
    $enable_hdfs        = hiera('dmlite::dav::params::enable_hdfs', false)
}
